### ISSUE TITLE
fine-tune latent-diffusion

### ISSUE THREAD

**Issue by ZerunLiu** [lxj616/stable-diffusion-qqbot#1]
您好，非常感谢您的工作，我在这里有一些问题希望您可以解答
1. 如果我想根据文本 d, 原图 i 和掩膜 m, 通过 fine-tune latent-diffusion 得到自己的扩散模型，我该在哪里入手呢？是fine-tune inpaint 模型还是 text-to-img 模型？这是因为我使用了您的代码，感觉 latent-diffusion模型根据上述三个条件生成的图片效果一般，所以想自己训练一下，稍微提高一下它在这项任务上的能力。
2. latent-diffusion没有经过这样的训练，也能根据文本、原图和mask生成符合语义的图像，您认为它的原因是什么呢？
如果您能回复我，不胜感激

**Comment by lxj616** [comment]
关于latent-diffusion的问题建议在latent-diffusion的issue区进行讨论，本repo只是一个从redis取任务的QQ机器人代码，本身不含latent-diffusion的功能，不过简单回答一下你的问题

1. 建议从latent-diffusion的repo和paper进行学习和训练，从compvis的示例中都自己训练一遍体验一下
2. 我不理解“没有这样的训练，也能”是什么意思，您可能需要去读一下DDIM的代码再提问？

本issue和本项目没有必然联系，close了，如果有latent-diffusion的问题请去latent-diffusion的repo下提问

**Comment by ZerunLiu** [comment]
好的  非常感谢您的回答
